services:
  hiring-manager-db:
    image: postgres:16-alpine
    container_name: hiring-manager-db
    environment:
      - POSTGRES_DB=hiringmanager_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - hiring-postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hiringmanager_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-net
    labels:
      io.portainer.accesscontrol.teams: skillab-all

  hiring-management-backend:
    build: .
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    container_name: hiring-management-backend
    depends_on:
      hiring-manager-db:
        condition: service_healthy
    ports:
      - "8890:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hiring-manager-db:5432/hiringmanager_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - shared-net
    labels:
      io.portainer.accesscontrol.teams: skillab-all

networks:
  shared-net:
    external: true

volumes:
  hiring-postgres-data:
    labels:
      io.portainer.accesscontrol.teams: skillab-all
