services:

  backend:
    build: ./backend
    container_name: skillab-hiring-backend
    restart: unless-stopped
    external_links:
      - employee-pulse-db:postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    volumes:
        - cvs-data:/data/file-storage/cvs
    ports:
      - "8087:8080"
    networks:
      - hr-shared-network
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skillab-hiring-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      # React must receive REACT_APP_* values at build/runtime
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    ports:
      - "8088:3000"
    networks:
      - hr-shared-network
      
networks:
  hr-shared-network:
    external: true

volumes:
  postgres-data:
    driver: local
  cvs-data:
    driver: local